In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
print(a[0]) 
print(a[4])
type(a)

1
5


numpy.ndarray

In [3]:
print(a)
print(a.size)
print(a.ndim)
print(a.shape)

[1 2 3 4 5]
5
1
(5,)


In [6]:
b = np.array([ [1,2],
               [3,4],
               [5,6] ])
a = np.array([ [7,8],
               [9,10],
               [11,12] ])

In [7]:
a + b

array([[ 8, 10],
       [12, 14],
       [16, 18]])

In [8]:
a * b

array([[ 7, 16],
       [27, 40],
       [55, 72]])

In [11]:
b = b.reshape(2,3)
np.dot(a,b)

array([[ 39,  54,  69],
       [ 49,  68,  87],
       [ 59,  82, 105]])

In [12]:
a + 2

array([[ 9, 10],
       [11, 12],
       [13, 14]])

In [13]:
a.mean()

9.5

In [14]:
b.max()

6

In [15]:
a.max()

12

In [16]:
a.min()

7