In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])
a * b

array([[ 10,  40,  90],
       [ 40, 100, 180]])

In [3]:
a + 4

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [4]:
a * 5

array([[ 5, 10, 15],
       [20, 25, 30]])

In [5]:
a + b

array([[11, 22, 33],
       [14, 25, 36]])

In [8]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30, 40])
print(a.shape)
print(b.shape)

(3,)
(4,)


In [9]:
a + b
# cannot be broadcasted

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [11]:
a = np.array([[1, 2], [3, 4]])
b = np.array([10])
print(a.shape)
print(b.shape)
a + b
# If one of the dimension is 1, it can be broadcasted

(2, 2)
(1,)


array([[11, 12],
       [13, 14]])

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[10, 20], [30, 40], [50, 60]])
a +